name: Reading Time
description: GitHub action to calculate medium-like reading times of markdown files and inserts to the top of the files.
author: harunrst
inputs:
  strategy:
    description: Select strategy to update your markdown files (all, paths, readme)
    required: false
    default: readme
  paths:
    description: Provide paths to look for when the strategy is "paths" (ie. docs|files)
    required: false
    default: .
  text-style:
    description: Text style (default, bold)
    required: false
    default: default
  text-align:
    description: Text align (left, center, right)
    required: false
    default: left
runs:
  using: node16
  main: dist/index.js
branding:
  color: white
  icon: clock
